### ISSUE TITLE
How to measure GMACs

### ISSUE THREAD

**Issue by shiyi-z** [dingfengshi/TriDet#15]
Hello, sorry to bother you!
can you share the method to measure the GMACs and latency as depict in table 6, I can't find that in the code
thanks very much!

**Comment by dingfengshi** [comment]
Hi！We use [fvcore](https://github.com/facebookresearch/fvcore/blob/main/docs/flop_count.md) to count the GMACs. It is notable that this code count one fused multiply-add as one flop, so the "flops" is actually the "MAC".

**Comment by shiyi-z** [comment]
thanks for your reply！
I have known how to use fvcore:
flops = FlopCountAnalysis(model, input) 
I would like to know what should be the tensor dimension of the input in the above function in this model

**Comment by dingfengshi** [comment]
> thanks for your reply！ I have known how to use fvcore: flops = FlopCountAnalysis(model, input) I would like to know what should be the tensor dimension of the input in the above function in this model

Hi, on THUMOS14, we use the same input as actionformer. Specifically, each video feature sequence is padded to 2304 in temporal dimension, and the dimensions of I3D features are 2048, so the shape of a video input should be (1, 2048, 2304)

**Comment by shiyi-z** [comment]
thanks very much for your answer , but,why do I get the following error reported after using the dimension you described?
![image](https://github.com/dingfengshi/TriDet/assets/79558156/d4872f03-597b-4d02-aa43-5372ac4772bf)
![image](https://github.com/dingfengshi/TriDet/assets/79558156/9f6087b1-4a5c-44b2-af6d-00b1c166fe35)
would you have some suggestions for modifications?

**Comment by dingfengshi** [comment]
> thanks very much for your answer , but,why do I get the following error reported after using the dimension you described? ![image](https://user-images.githubusercontent.com/79558156/248485674-d4872f03-597b-4d02-aa43-5372ac4772bf.png) ![image](https://user-images.githubusercontent.com/79558156/248485695-9f6087b1-4a5c-44b2-af6d-00b1c166fe35.png) would you have some suggestions for modifications?

The input for the model is a list of dict which contain the video information. You can try measure each components in `forward` function in `meta_archs.py`.
