### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by hongminglin08** [dingfengshi/TriDet#16]
hello, when I run epic_verb_slowfast_script.sh, it shows loss nan and cls_loss nan, is that correct?
![image](https://github.com/dingfengshi/TriDet/assets/52478955/674722e2-b445-4257-99b2-6aed940f07e8)

**Comment by dingfengshi** [comment]
Hi, that's not correct and I can not reproduce the problem. Could you please check your data?

**Comment by hongminglin08** [comment]
> Hi, that's not correct and I can not reproduce the problem. Could you please check your data?
I downloaded this dataset from the following Baidu Cloud link, is this?
![image](https://github.com/dingfengshi/TriDet/assets/52478955/30e49883-d19b-4631-899a-2dbc1b9ceaab)

**Comment by dingfengshi** [comment]
yes, have you changed any part of the code?

**Comment by hongminglin08** [comment]
> yes, have you changed any part of the code?

no, I only downloaded and unpacked the dataset, leaving the rest unchanged

**Comment by dingfengshi** [comment]
Could you please provide some information about your environment? Do this situation only happen on EPIC-verb dataset?

**Comment by hongminglin08** [comment]
> Could you please provide some information about your environment? Do this situation only happen on EPIC-verb dataset?

solved, It's really the environment that causes the problem

**Comment by dingfengshi** [comment]
> > Could you please provide some information about your environment? Do this situation only happen on EPIC-verb dataset?
> 
> solved, It's really the environment that causes the problem

ok.
