### ISSUE TITLE
use_deterministic_algorithms() got an unexpected keyword argument 'warn_only'

### ISSUE THREAD

**Issue by WalterWangRevo** [dingfengshi/TriDet#2]
Hello, I found line 32 in train_utils.py :use_deterministic_algorithms() got an unexpected keyword argument 'warn_only', my Pytorch version is 1.9.0。

**Comment by dingfengshi** [comment]
You can simply remove this argument and change this line to ` torch.use_deterministic_algorithms(True)`. This argument appeared in pytorch version 1.11. Thank you for your reminder!

**Comment by dingfengshi** [comment]
Our code needs to run on the version of pytorch1.11. There may be some problems in lower versions.
