### ISSUE TITLE
Data acquisition problem

### ISSUE THREAD

**Issue by YCA-eng** [dingfengshi/TriDet#4]
Thanks for your excellent work. How to download i3d_feature and slowfast_feature in the same format as yours.

**Comment by YCA-eng** [comment]
i3d_feature: https://drive.google.com/file/d/1zt2eoldshf99vJMDuu8jqxda55dCyhZP/view
Unzip to the deta path
bash is ok

**Comment by dingfengshi** [comment]
Hi! For the slowfast_feature, you need to download all the files end with (.validation.tar.bz2.* and .training.tar.bz2.*) in the folder `hacs-data/features` from their BaiduYun link.
Then you can merge the all the volumes and unzip each file, for example 
```bash
# merge volumes
cat slowfast101.epoch9.87.52.finetune.pool.t.keep.t.s8.validation.tar.bz2* > slowfast101.epoch9.87.52.finetune.pool.t.keep.t.s8.validation.tar.bz2

#unzip the new file
tar xjvf slowfast101.epoch9.87.52.finetune.pool.t.keep.t.s8.validation.tar.bz2
```
You can try that, sorry I have forgotten the specific command executed at that time. If there is anything wrong with this command please let me know, thank you!
