### ISSUE TITLE
help with decode_offset function

### ISSUE THREAD

**Issue by zivnachum** [dingfengshi/TriDet#5]
Hi, thanks for the great code base and paper!

I'm already using Actionformer and now I'm experimenting on TriDet too. When using Actionformer, I made a change in the code so the loss and predictions will be reported in both train and eval mode, and then I can keep track on loss and mAP for train and validation.
I tried to make a similar adjustment in TriDet, but encountered an issue in the function `decode_offset` in `meta_archs.py`.
The fact that there's a different behavior for train and eval makes it harder to get predictions for train too.
Any chance you give some explanation on what this function is doing?

Thanks!

**Comment by dingfengshi** [comment]
I have updated some comment for `meta_arch.py`. Thanks for your reminder!
