### ISSUE TITLE
the loss is 0 when training model with custom dataset

### ISSUE THREAD

**Issue by OpenSorceYCW** [dingfengshi/TriDet#6]
Thanks for your excellent work. I meet the problem when I train the model with custom dataset, can you give me some advice to solve it. 
![image](https://user-images.githubusercontent.com/22862171/229720770-8f2de863-ae5c-4925-b9e1-6b845867faf2.png)
thank you, I am looking for you reply!

**Comment by OpenSorceYCW** [comment]
Thank your very much!  Another problem, I am puzzled about function of  truncate_feats in https://github.com/dingfengshi/TriDet/blob/master/libs/datasets/thumos14.py#L182,  whether to increase sample diversity?
 can you explain it detail, thank you!

**Comment by OpenSorceYCW** [comment]
ok, thank you for your reply!

**Comment by dingfengshi** [comment]
Issue has been sloved
