### ISSUE TITLE
some problem in computing offset loss in ctr_giou_loss_1d

### ISSUE THREAD

**Issue by OpenSorceYCW** [dingfengshi/TriDet#8]
I found some problem in computing offeset loss, path is:  https://github.com/dingfengshi/TriDet/blob/master/libs/modeling/losses.py#L91, it seems lkis = torch.max(lp, lg)  rather than  lkis = torch.min(lp, lg) ?  I can not understand it, please check it , thank you!

**Comment by dingfengshi** [comment]
Hello, the output of the prediction are the offsets (>=0) from a central point, rather than the left and right coordinates of a segment. Therefore, torch.min(lp, lg) will represent the point closer to the central points.
