### ISSUE TITLE
how to deploy the model？

### ISSUE THREAD

**Issue by OpenSorceYCW** [dingfengshi/TriDet#9]
if i want to do inference with trt, how to restruct network struct, can you give me some advice? 
in addition, I meet some error in onnx2trt which message is that If_1387_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape, I am looking for your reply! thanks again.

**Comment by dingfengshi** [comment]
I’m sorry, I haven’t used onnx2trt before so I can’t provide any advice for this problem.
